version: "3.6"

volumes:
  postgres-data:
  redis-data:
  azurite-data:

services:
  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - 10000:10000
      - 10001:10001
    volumes:
      - azurite-data:/data

  postgres:
    image: postgres:alpine
    volumes:
      - ./config/initdb:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=p@ssw0rd

  pgpouncer:
    image: mcr.microsoft.com/azure-oss-db-tools/pgbouncer-sidecar:latest
    ports:
      - 5432:5432
    volumes:
      - ./config/pgbouncer:/etc/pgbouncer/
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
